; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_devkitc_serial

[common_env_data]
build_unflags =
  -fno-exceptions
build_flags =
  -Wno-unknown-pragmas
  -Wunused-variable
  -D CORE_DEBUG_LEVEL=3
  -D MQTT_MAX_PACKET_SIZE=256
  -Wdeprecated-declarations
  -fexceptions
lib_ldf_mode = deep+
lib_deps =
  MySensors@>=2.3.2
  ESP32Async/AsyncTCP@^3.3.2
  ESP32Async/ESPAsyncWebServer@^3.6.0
monitor_filters =
  default
  time
  colorize


[env:esp32_devkitc_serial]
platform = espressif32 @ 6.10.0
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
build_flags =
	${common_env_data.build_flags}
	-D USE_ESP32
	; -D MY_DEBUG
	; -D MY_CORE_ONLY
	-w
	-Wunused-parameter
	-Wdeprecated-declarations
lib_deps = ${common_env_data.lib_deps}
upload_speed = 230400
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
monitor_speed = 115200
monitor_filters = 
	${common_env_data.monitor_filters}


[env:esp32_devkitc_ota]
platform = espressif32 @ 6.10.0
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
build_flags =
	${common_env_data.build_flags}
	-D USE_ESP32
	; -D MY_DEBUG
	; -D MY_CORE_ONLY
	-w
	-Wunused-parameter
	-Wdeprecated-declarations
lib_deps = ${common_env_data.lib_deps}
upload_protocol = espota
upload_port = 192.168.2.188
upload_speed = 460800
monitor_speed = 115200
monitor_filters =
	${common_env_data.monitor_filters}
